### ISSUE TITLE
please update `latest` tag on npm

### ISSUE THREAD

**Issue by timoxley** [shama/gaze#178]
```
npm info gaze dist-tags.latest
npm http request GET https://registry.npmjs.org/gaze
npm http 304 https://registry.npmjs.org/gaze
0.5.1
```

should probably be 0.6.4.

**Comment by shama** [comment]
`0.6.4` doesn't work with io.js or node v0.12 among some other issues (it's the version where I switched to native bindings). The [navelgazer](https://github.com/shama/gaze/tree/navelgazer) branch is taking awhile for me to complete which will provide support.

So, atm, `0.5.1` is more stable and works with io.js and node v0.12, although slower and more CPU intensive. I've tagged latest to `0.5.1` to minimize friction until I can get the navelgazer branch green.

**Comment by johngeorgewright** [comment]
:+1: Yes please!

**Comment by am11** [comment]
@shama, over at node-sass we are getting suggestions to switch to chokidar or alternative file watchers (https://github.com/sass/node-sass/issues/636, not to mention those also have issues and limitations which glaze overcame long time ago). If this is still under active development and the future is gonna glow brighter with gaze, I will vote to stay. :)

**Comment by shama** [comment]
@am11 Yep gaze is still under active development, I am just slow. The latest version of chokidar is looking good though and now supports glob patterns. Feel free to use whichever library works best for you.

**Comment by marlun** [comment]
Is 0.5.* still considered the most stable version? I'm getting warnings that a deprecated version of lodash is used when installing node-sass and they won't update their version of gaze untill til dist-tag is uppdated. Just curious about how it's looking, thanks!

**Comment by jorrit** [comment]
Maybe a v0.5.3 that updates lodash?

**Comment by shama** [comment]
How about this, let's release an updated `0.5` as `1.0.0` stable. This will fix the confusion with why `0.5` is tagged latest and let us fix these things so nobody has to wait for the `navelgazer` branch to land, sound good?

Any objections? /cc @joshperry

**Comment by jorrit** [comment]
Sounds like a great plan! The only downside is that it will require other modules to actively upgrade their deps but in the long run having a nice and stable 1.0 and no 0.5/0.6 confusion is preferable.

**Comment by bradchesney79** [comment]
@jorrit https://github.com/shama/gaze/pull/208 -- choosing the upgraded globule would update lodash to 2.4.x or something similar.

Now that I've seen more of the issues, it seems as maintainer is stuck between a rock and a hard place. Can't raise the release in npmjs to the 0.6 branch because it isn't quite ready for prime time and cannot upgrade the globule dependency in the 0.5 series because of the lodash major version bump (which may cause breaks).

I guess my only questions are:

Are there breaking changes if globule were updated? The tests seem to pass. How many of these people are depending on the fairly old libraries-- do the breaking changes even affect gaze?

Is it merely that the existing unit tests must pass for the range of supported node/iojs versions for release?

**Comment by shama** [comment]
@bradchesney79 It's mostly because this library gets downloaded 3M times a month. I want to avoid breaking people's workflows. The changes to `globule` and its dependencies don't look too bad to me either but I wouldn't really know until I release and break it, which for that many users would be bad.

I think `0.5` has proven itself to be extremely stable so `1.0.0` will be just updating the deps and very minor changes. In which people can selectively upgrade being aware it *could* potentially break their workflow (just likely wont).

Then just keep on working on `navelgazer` (tests passing, pre-built binaries in place, double check on major projects that use it as a dependency) and then release a fully vetted `2.0.0`.

**Comment by am11** [comment]
@shama, this is the best strategy for 1.0. Depending on native module is going to be a major change, which may break folks on less-commonly used OSes (SunOS, NetBSD etc.) and many other reasons.

Generally, one thing we should realize that date-time and file-system watcher are two long standing problems which almost every runtime/framework is struggling with. There is no decent native library which abstracts out all the varied file systems' observing mechanics and work like a champ.

**Comment by jorrit** [comment]
@shama: any progress on this?

**Comment by shama** [comment]
Latest is `1.1.0`
