### ISSUE TITLE
Is this alive?

### ISSUE THREAD

**Issue by jzaefferer** [shama/gaze#182]
Looking at the lack of releases and open issues piling up, I wonder if this project is still alive. Considering actively maintained alternatives like [chokidar](https://www.npmjs.com/package/chokidar), it might be best to deprecate this package and point users at alternatives. Would also reduce fragmentation and duplication.

**Comment by shama** [comment]
OSS doesn't live nor die. It is only useful to you or not useful.

Gaze only exists because Chokidar didn't live up to it's previous promises in it's readme. If you've been following development on chokidar for the past 3 years as I have, it hasn't always been "active". Case and point read this: https://github.com/paulmillr/chokidar/issues/138#issuecomment-57974826 but even before that it had lulls and active periods.

The past few months chokidar has made leaps and bounds of improvement. @es128 has basically been fixing everything and even just added glob support. This is fantastic because a lot of projects I use have chokidar as a dep.

But if you believe gaze is just a duplicated chokidar, you're naive. They operate incredibly differently under the hood. I'll consider deprecating gaze as soon as chokidar passes all of gaze's tests cases across Windows/OSX/Linux.

But even then, what's is the point? Fragmentation? Should we deprecate jQuery because we have `querySelector()`? There are hundreds of file watching libraries on npm. Are you going to naively tell all of them to deprecate too?

More options are better than one. Use a library if it is useful or don't. This isn't highlander.
