### ISSUE TITLE
Lodash deprecation warning

### ISSUE THREAD

**Issue by SgtPooki** [shama/gaze#207]
I realize that this isn't super high-priority, but I wanted to open this issue just to say that as soon as https://github.com/cowboy/node-globule/pull/22 makes it through, we should make a gaze@0.5.3 that just bumps up the node-globule dependency. Or maybe some other version tag until gaze@^0.6.0 gets working.

**Comment by SgtPooki** [comment]
Related to https://github.com/gulpjs/glob-watcher/issues/23

**Comment by chicoxyzzy** [comment]
@shama can you please fix it?

**Comment by shama** [comment]
Please see https://github.com/lodash/lodash/issues/1686 and thank @phated for stewarding lodash being un-deprecated.

**Comment by jdalton** [comment]
I actually just reduced the deprecation from all packages < 3 to those < 2.

**Comment by chicoxyzzy** [comment]
BTW there is 1.0.2 version in dependencies so issue is not resolved. Also something is wrong with `gaze` version itself. Look at https://github.com/shama/gaze/releases and version at npm https://www.npmjs.com/package/gaze

**Comment by shama** [comment]
@chicoxyzzy Sorry there isn't anything I can do from here anyways. `lodash` is a dependency of `globule` and I don't have commit access to that project.

**Comment by chicoxyzzy** [comment]
@shama actually you can =) `globule` 0.2.0 uses `lodash` ~2.4.1 but `gaze` 0.5.2 (which is unexpectedly the last version from npm) [uses](https://github.com/shama/gaze/blob/v0.5.2/package.json#L31) `globule` 0.1.0 which uses outdated version of `lodash`

**Comment by shama** [comment]
`0.5.2` is the latest on npm because it is the most stable in the current Node.js environments atm.

You're right, I could minor bump globule `0.2.0` and patch bump gaze `0.5.3` but that doesn't seem like a very safe thing to do. There are probably other things I can do to remove a silly message displayed when installed but it seems like it would potentially create more problems and confusion, rather then just telling people to ignore that silly message for now.

Any time I put towards this project is going to be on this branch: https://github.com/shama/gaze/tree/navelgazer Which is slowly but surely moving along to a `1.0.0` release.

Just a note, if you're running into this with gulp, they no longer use this library so you may just need to upgrade gulp. That is just a guess though as I don't follow development there anymore.

**Comment by chicoxyzzy** [comment]
I've ran into it with `webpack 2.0.2-beta`. Good to there is some progress with future version!

**Comment by shama** [comment]
Oh weird, I thought webpack uses `chokidar` too?
